### ISSUE TITLE
Fail to open sextractor

### ISSUE THREAD

**Issue by secretgardeninmyword** [astromatic/sextractor#15]
I have installed old-version sextractor and it works well. But when I update it (install the newest-version sextractor), I can't even open it ! I follow the "./configure, make, make install" procedure and it seems well. But when I try to open it, it tell me that:
####
sex: error while loading shared libraries: libsatlas.so.3: cannot open shared object file: No such file or directory
####
I have already install libatlas and libatlas-basic and libatlas-basic folder contains  libsatlas.so.3. I'm new to linux but i realize that the file " libsatlas.so.3'  isn't shared to sextractor by some reason. Or can I move  libsatlas.so.3 to the designated folder manually?
Thanks

**Comment by cmarmo** [comment]
Hi @secretgardeninmyword , `./configure --help` will show you all the options available to customize your installation.
In particular, as you know where your `libsatlas.so.3` is, you might want to use the two options
```
  --with-atlas-libdir=<ATLAS library path>
                          Provide an alternative path to the ATLAS library
  --with-atlas-incdir=<ATLAS include dir>
                          Provide an alternative path to the ATLAS include
                          directory
```
If the issue is still there after configuring those options do you mind clarifying which linux distribution are you using?
Also, how previous versions have been installed on your system and have you cleaned up before installing the last version?
Thanks.

**Comment by secretgardeninmyword** [comment]
I have just figure it out. I use strace -f to find out why it has miss that lib. The result is that this app search the wrong path to find that lib, and I move that lib into the location which the app proposed. And finally, I have run it successfully.

**Comment by cmarmo** [comment]
I'm glad to know you have found a solution, just be aware that manually moving libraries on your system will probably produce side effects on other installations. `./configure` options are a safer solution.
Anyway if you are happy I think this one could be closed. :)
