### ISSUE TITLE
rename package and CLI tools

### ISSUE THREAD

**Issue by beckermr** [astromatic/sextractor#8]
Per discussion here https://github.com/conda-forge/staged-recipes/pull/8764, it is well past time that we rename this package and the associated CLI tool. As this appears to be the main source repo now, I think this issue is the best spot.

**Comment by beckermr** [comment]
Some suggestions for the package name and the CLI tool:

`srcextractor` and `srcex`

`source-extractor` and `source-extractor`

**Comment by hbouy** [comment]
Thousands of professionnal and amateurs astronomers happily use it as it is every day for over  23 yr without any issue about the name. Should a puritan minority dictate an important change to the overwhelming majority?

**Comment by beckermr** [comment]
Please see the thread in the linked issue above.

**Comment by ebertin** [comment]
Conda-forge developers are certainly free to use whatever renaming they find appropriate in their recipes if they decide that some names here or there dont meet their code of conduct.
However I am not keen on propagating such breaking changes upstream (i.e., here), beginning with the package name.

**Comment by beckermr** [comment]
OK @ebertin. The thread above seemed to imply you were ok renaming things here. I don't agree but I also am not the developer. Feel free to close this issue if you would like.

**Comment by teake** [comment]
> OK @ebertin. The thread above seemed to imply you were ok renaming things here. I don't agree but I also am not the developer. Feel free to close this issue if you would like.

Sorry, that inferred implication comes from me not clearly quoting @ebertin in https://github.com/conda-forge/staged-recipes/pull/8764#issuecomment-510034953. I have clarified the post. My apologies for creating the misunderstanding.

**Comment by beckermr** [comment]
No worries @teake! This discussion, while disappointing to me personally, has clarified the status of the package in terms of conda-forge distribution.

**Comment by teake** [comment]
@ebertin Please allow me to say a few more words, and then I'll give it a rest.

I would not dare to ask you to change the name of your upstream. As @hbouy has rightly pointed out there is simply too much history behind it. Besides, if someone would come in out of the blue and ask me to change the name of my project, even if it didn't have that history, I would probably say no.

All I'm asking you now is to, at some point in the future, consider renaming the `sex` command to something that people might find less offensive. (The fact that `sex` is offensive is could up for discussion for some. But to be honest I've always found it a peculiar acronym). A good time for this would be when there are future breaking changes in algorithms that warrant a 3.0 release anyway. As @beckermr has proposed in https://github.com/conda-forge/staged-recipes/pull/8764#issuecomment-510047057 there could also be a migration period leading up this breaking change, where both the new and old command name co-exists.

I'm hoping you'll give this some thought. SExtractor is a key piece of software for a wide range of astronomers, and conda-forge is a key distribution channel. IMHO, it would be a missed opportunity if the two do not find any overlap.

**Comment by ebertin** [comment]
Hi @teake, thanks for taking the time to discuss the "issue".
Indeed changing the package name would certainly be a major issue and is currently a no-no for me. Thousands of links and papers refer to it. The software has been registered under that name. However I agree with you about the name of the executable. Although convenient, nowadays some people may feel uncomfortable with it. Switching to `sextractor` would be the most logical choice to me.
Please feel free to file a pull-request if this fine with you.

**Comment by beckermr** [comment]
Thank you @ebertin! I am glad we could work something out!

**Comment by jradavenport** [comment]
Hi all,
I wanted to revisit this a bit, given the excellent discussion we had yesterday on the `sextractorxx` fork yesterday: https://github.com/astrorama/sextractorxx/issues/136

As you note above, Source Extractor has been used for +20 years, is THE benchmark for first-look and survey photometry, and is widely adopted by professionals and amateurs alike.

However, I disagree strongly with both the notions stated above that a _minority_ of people take issue with the name (or more specifically the abbreviations, and CLI as addressed above), and that those with an issue are _puritans_. Just because you don't find it offensive doesn't make it not offensive to some (or many). `SExtractor` has been a continuous bad joke that we tip-toe around with students - especially junior women - over the 15 years I've been in the field. I have first-hand experience with people being uncomfortable or upset by the name, and if I were to name my software like this at a public US institution today I would be opening myself to unprofessional workplace complaints. This recent chatter on GitHub and elsewhere _can't_ be the first time you've heard such feedback. 

Making our field and tools welcoming (e.g. less offensive) isn't just caving to a picky or hyper-sensitive cohort of newcomers.  We have to continuously improve and build the community we want to exist, and which reflect our values. Therefore I implore you to reconsider renaming the package. I think this isn't a firestorm, but a genuine opportunity to do a good deed for the community.

I think `Source Extractor` with the abbreviation `SE` maintains the brand recognition, and would be welcomed and easily adopted. I know renaming the whole package is a major refactor, and can't happen overnight. But beginning a process of goodwill and improvement can only be a healthy evolution for this venerable code.

**Comment by PaulPrice** [comment]
It's true that there's a **lot** invested in the current naming, but I would suggest that this fact actually provides a very good motivation to change the name: the great cost to pay in renaming would make the gesture incredibly significant throughout all of astronomy. This is a wonderful opportunity to lead the entire astronomical community in making our field inclusive and welcoming.

**Comment by arm2arm** [comment]
just as above: to type on the command line **se** is the best choice, but for some flyers Sextractor was really eye-poping.

**Comment by ebertin** [comment]
Hi all,
thank you for the heads up. If it is really makes people unhappy, I certainly won't oppose a renaming.
I have had a poor record of maintaining the Astromatic public packages and addressing support requests over the past years, so I guess the best would be handing over the keys to anyone who is willing to do the job, and decide swiftly what renaming scheme would be best. This is the main reason why the package in on GitHub. It is supposed to be collaborative, and can be forked.
SExtractor is definitely not a "brand", and is covered with the GPL. Which essentially means you can do whatever you want with it, as long as it remains GPL and you keep a copy of the original license somewhere together with the modified code (indicating what changes were made). So I think you can rename the package, change all the variable names to anything you want and redistribute it without my consent, but thank you for asking.
